#!/usr/bin/env bash

#tag_names=( {1..10} )
#tag_keys=( {1..10} 0)

#hc rename default "${tag_names[0]}" || true
#for i in ${!tag_names[@]} ; do
#    hc add "${tag_names[$i]}"
#    key="${tag_keys[$i]}"
#    if ! [ -z "$key" ] ; then
        # first check if the tag is locked to some monitor.
        # if so, first focus the monitor
#        hc keybind "$Mod-$key" \
#            chain , silent substitute M tags."$i".my_monitor \
#                        focus_monitor M \
#                  , use_index "$i"
#        hc keybind "$Mod-Shift-$key" move_index "$i"
#    fi
#done

#herbstclient keybind $Mod-t chain \
#    , new_attr string tags.focus.my_monitor \
#    , substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
#    , try and \
#        . compare monitors.focus.name != "" \
#        . substitute M monitors.focus.name \
#                set_attr tags.focus.my_monitor M

#herbstclient keybind $Mod-Shift-t \
#    remove_attr tags.focus.my_monitor

#lock_to_monitor() {
#    herbstclient chain \
#        , new_attr string tags.by-name."$1".my_monitor \
#        , set_attr tags.by-name."$1".my_monitor "$2"
#}

#lock_to_monitor 1 0
#lock_to_montior 2 0
#lock_to_monitor 3 0 
#lock_to_monitor 4 0
#lock_to_monitor 5 0

#lock_to_monitor 6 1
#lock_to_monitor 7 1
#lock_to_monitor 8 1
#lock_to_monitor 9 1
#lock_to_monitor 10 1 

~/.config/herbstluftwm/theme.sh 
~/.config/herbstluftwm/keybinds.sh 
~/.config/herbstluftwm/setup.sh 
